<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function profile2_ctools_ctools_plugin_api( $module, $api ) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function profile2_ctools_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
